pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('Jenkins_CICD') {
                    bat 'python --version'
                    bat 'python -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Jenkins_CICD') {
                    bat 'python -m pytest -q'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Jenkins_CICD') {
                    bat 'python -m py_compile app.py'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('Jenkins_CICD') {
                    bat 'if not exist deploy mkdir deploy'
                    bat 'copy /Y app.py deploy\\app.py'
                    bat 'copy /Y requirements.txt deploy\\requirements.txt'
                    echo 'Deployment Successful'
                }
            }
        }
    }
}